#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
TARGETS=`cat ${SCRIPTPATH}/targets`

for TARGET in $TARGETS;
do
    echo "Entering ${TARGET}"
    cd ${TARGET};
    make clean
    cd -
    echo "Exiting ${TARGET}"
done
