#!/bin/sh

# Clones all the Verificatum mix-net repositiories from GitHub.

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

TARGETS="verificatum-gmpmee verificatum-vmgj verificatum-vec verificatum-vecj verificatum-vcr verificatum-vmn"
for TARGET in $TARGETS;
do
    git clone git@github.com:verificatum/${TARGET}.git
done
