#!/bin/sh

# Copyright 2008-2018 Douglas Wikstrom
#
# This file is part of Verificatum Mix-Net (VMN).
#
# VMN is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VMN is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with VMN. If not, see <http://www.gnu.org/licenses/>.

# A cache is supposed to return cached contents if any, and otherwise
# look up information from the underlying data source. Unfortunately,
# Linux does not do this for library locations, so we may have to run
# an update explicitly and this has to be done as super user.
#
# Needless to say this works correctly, e.g., on OpenBSD, where this
# command does somethings quite different, so we need to avoid running
# it if we are not on a Linux.

if test `uname` = "Linux";
then
    if test -f /sbin/ldconfig;
    then
	sudo /sbin/ldconfig -v
    fi
fi